/**
 * Returns a 'motivating' message.
 */
export const generateMotivationQuips = () => {
  const quips = [
    '"Code it or catch these hands."',
    '"Ship it or skip it."',
    '"Commit or quit."',
    '"More coding, less yapping."',
    '"Spanish or vanish. Code or explode."',
    '"Knowing you, you\'d push to main."',
    '"The bugs won\'t fix themselves. Neither will you, apparently."',
    '"Your git history is a cry for help."',
    '"Clock\'s ticking. So is your eye."',
    '"Less talking. More shipping."',
    '"You\'ve been on this file for 40 minutes. Pick a variable name."',
    '"The deadline doesn\'t care about your feelings."',
    '"Type faster. Think later."',
    '"Touch grass after the demo."',
    '"Sleep is for the deployed."',
    '"Your mom thinks you\'re productive right now."',
    '"One more tab open and you\'re cooked."',
    '"The diff doesn\'t lie. You do."',
    '"Hydrate or diedrate."',
    '"You will finish this. Probably."',
    '"Still here? Respect. Barely."',
    '"Code now. Cry later."',
    '"Fix the bug or become one."',
    "\"You've got this. No you don't. Yes you do.\"",
    '"Push something. Anything. Please."',
    '"The repo is judging you."',
    '"Somewhere, your teammate is actually working."',
    '"This is fine. It\'s not fine. Code anyway."',
    '"Leetcode couldn\'t prepare you for this."',
    '"You will not die on this hill. The hill will die on you."',
    '"Merge or perish."',
    '"Debug or be debugged."',
    '"Your future self will hate you for this. Write the comment."',
    '"Stack Overflow can\'t save you now."',
    '"ChatGPT is not your pair programmer. Stop it."',
    '"The compiler has no mercy. Neither do I."',
    '"You have 3 hours. Act like it."',
    '"Branching strategy: chaos. Fix that."',
    "\"You named it 'data2'. We need to talk.\"",
    '"A TODO is just a bug with a bow on it."',
    '"You will not google that again. You will google that again."',
    '"npm install won\'t fix your life choices."',
    "\"That's not a feature. That's a bug with confidence.\"",
    '"Indent your code. Have some self-respect."',
    '"You just broke the build. Own it."',
    '"Every senior dev was once you. They\'re still scared too."',
    '"Refactor or regret. Your call."',
    '"There are two kinds of code: working and yours."',
    '"The semicolon was right there."',
    "\"You've restarted the server 6 times. It's not the server.\"",
    '"Close a tab. You\'re not using all of those."',
    '"Your variable names are a hate crime."',
    '"Done is better than perfect. You\'re not even close to either."',
    '"Ship the feature. Apologize later."',
    '"It worked on localhost. Bold claim for a demo."',
    '"Console.log is not a debugger. Use a debugger."',
    '"You copy-pasted the bug too."',
    "\"Write the test. Or don't. We'll all know.\"",
    '"You\'re one off-by-one error away from a breakdown."',
    '"The light at the end of the tunnel is a merge conflict."',
  ];

  return quips[Math.floor(Math.random() * quips.length)];
};
